In [1]:
import geopandas
import pandas as pd

In [3]:
Kreuzberg_stations_df = pd.read_csv("FilteredDataset/Kreuzberg_stations.csv")
Kreuzberg_stations_df

,Unnamed: 0,stop_id,stop_name,typ,location,point,in_linien,wikidata_id
0,0,194617,Anhalter Bahnhof,s-bahn,"['52.503055555556', '13.381944444444']",POINT (13.381944444444 52.503055555556),"['KBS 103', 'KBS 104a', 'KBS 105a']",Q111324573
1,1,194618,Anhalter Bahnhof,straßenbahn,"['52.50453275122', ' 13.382326534592197']",POINT (13.382326534592197 52.50453275122),['1'],NaN
2,2,194619,Anhalter Bhf.,straßenbahn,"['52.50449054956299', ' 13.382289924849571']",POINT (13.382289924849571 52.50449054956299),['21'],NaN
3,3,194626,Baerwaldstr. Ecke Gneisenaustr.,straßenbahn,"['52.490331369885155', ' 13.400299112902015']",POINT (13.400299112902015 52.490331369885155),['99'],NaN
4,4,1946158,Franz-Mehringstr.,omnibus,"['52.49508128500466', ' 13.389323838894562']",POINT (13.389323838894562 52.49508128500466),['1'],NaN
...,...,...,...,...,...,...,...,...
717,717,19892573,Wilmsstr.,autobus,"['52.4952693941617', ' 13.404256096296391']",POINT (13.404256096296391 52.4952693941617),['28'],NaN
718,718,19892598,Wrangelstr.,autobus,"['52.50349055126274', ' 13.43002511023885']",POINT (13.43002511023885 52.50349055126274),['28'],NaN
719,719,19892607,Yorckstr.,autobus,"['52.49290342432449', ' 13.387649041870562']",POINT (13.387649041870562 52.49290342432449),['28'],NaN
720,720,19892609,Yorckstr.,u-bahn,"['52.493056', '13.370833']",POINT (13.370833 52.493056),['7'],Q12011022
721,721,19892664,katzbachstr.,autobus,"['52.49157231856929', ' 13.376684416851326']",POINT (13.376684416851326 52.49157231856929),['19'],NaN

In [48]:
Wilmersdorf_stations_df = pd.read_csv("FilteredDataset/Wilmersdorf_stations.csv")
Wilmersdorf_stations_df

,Unnamed: 0,stop_id,stop_name,typ,location,point,in_linien,wikidata_id
0,0,194645,Berlinerstr. Ecke Kaiserallee,straßenbahn,"['52.487339334357976', ' 13.3309375952067']",POINT (13.3309375952067 52.487339334357976),['3'],NaN
1,1,1946147,Fehrbellinerplatz,straßenbahn,"['52.49032472677901', ' 13.314317300484289']",POINT (13.314317300484289 52.49032472677901),"['3', '62']",NaN
2,2,1946148,Fehrbellinerplatz,u-bahn,"['52.490277777778', '13.314444444444']",POINT (13.314444444444 52.490277777778),['A2'],Q663245
3,3,1946219,Heidelbergerplatz,u-bahn,"['52.479808333333', '13.313236111111']",POINT (13.313236111111 52.479808333333),['A2'],Q21777872
4,4,1946238,Hohenzollerndamm,straßenbahn,"['52.48810038121649', ' 13.300864203881337']",POINT (13.300864203881337 52.48810038121649),['62'],NaN
...,...,...,...,...,...,...,...,...
472,472,19892426,Uhlandstr.,autobus,"['52.49371867338476', ' 13.323534918277579']",POINT (13.323534918277579 52.49371867338476),['50'],NaN
473,473,19892454,Waghäuselerstr.,autobus,"['52.48391612851139', ' 13.330974926061291']",POINT (13.330974926061291 52.48391612851139),['74'],NaN
474,474,19892503,Weimarischestr.,autobus,"['52.48174499330689', ' 13.324245601196424']",POINT (13.324245601196424 52.48174499330689),['74'],NaN
475,475,19892541,Wiesbadenerstr.,autobus,"['52.472139703970726', ' 13.3143773020809']",POINT (13.3143773020809 52.472139703970726),"['1', '16', '86']",NaN
476,476,19892646,Zoppoterstr.,autobus,"['52.473296547988454', ' 13.29898680384016']",POINT (13.29898680384016 52.473296547988454),['86'],NaN

In [5]:
line_stops_df = pd.read_csv("PublicTransitDataset/line_stops.csv")
line_stops_df

       line_id  stop_order   stop_id
0        19461           0   1946151
1        19461           1   1946158
2        19461           2   1946212
3        19461           3   1946325
4        19461           4   1946257
...        ...         ...       ...
28977  1989198           8    198944
28978  1989198           9   1989501
28979  1989198          10  19891912
28980  1989198          11  19891172
28981  1989198          12  19891860

[28982 rows x 3 columns]

In [25]:
lines_df = pd.read_csv("PublicTransitDataset/lines.csv")
lines_df

,line_id,jahr,linien_name,typ,dauer (min),ost_west,frequenz,länge (km),start,ziel
0,19461,1946,1,autobus,NaN,both/unkown,25,NaN,Flughafen,Alt-Friedrichsfelde
1,19462,1946,1,straßenbahn,15.0,both/unkown,10,NaN,Hackescher Markt,Anhalter Bahnhof
2,19463,1946,17,autobus,NaN,both/unkown,30,NaN,"Zehlendorf, Rathaus",Stölpchensee
3,19464,1946,21,straßenbahn,15.0,both/unkown,6,NaN,Wiebestrasse,Anhalter Bhf.
4,19465,1946,23,straßenbahn,20.0,both/unkown,10,NaN,Rosenthal,Fennstrasse
...,...,...,...,...,...,...,...,...,...,...
2094,1989194,1989,95,autobus,33.0,ost,20,NaN,Greifswalder Strasse,S-Bhf. Marzahn
2095,1989195,1989,96,autobus,29.0,ost,15,NaN,S-Bhf. Nöldnerplatz,S-Bhf. Nöldnerplatz
2096,1989196,1989,97,autobus,15.0,ost,0,NaN,Rangierbahnhof,Rangierbahnhof
2097,1989197,1989,98,autobus,7.0,ost,0,NaN,Franz-Stenzer-Strasse,Arbeitsstättengebiet Marzahn
2098,1989198,1989,99,autobus,39.0,ost,20,NaN,Greifswalder Strasse,S-Bhf. Friedrichsfelde Ost

In [11]:
print(list(Kreuzberg_stations_df["stop_id"]))

[194617, 194618, 194619, 194626, 1946158, 1946159, 1946160, 1946175, 1946176, 1946182, 1946183, 1946184, 1946204, 1946212, 1946213, 1946257, 1946281, 1946283, 1946300, 1946325, 1946347, 1946429, 1946474, 1946475, 1946494, 1946624, 1946625, 195130, 195131, 195132, 1951209, 1951246, 1951266, 1951283, 1951285, 1951286, 1951318, 1951319, 1951326, 1951327, 1951328, 1951389, 1951425, 1951428, 1951429, 1951518, 1951519, 1951520, 1951521, 1951522, 1951526, 1951528, 1951626, 1951627, 1951707, 1951708, 1951730, 1951797, 1951798, 1951829, 1951833, 1951837, 1951849, 1951902, 1951928, 1951938, 195644, 195645, 195646, 195664, 1956271, 1956272, 1956319, 1956360, 1956366, 1956367, 1956368, 1956408, 1956418, 1956419, 1956500, 1956533, 1956534, 1956555, 1956561, 1956562, 1956563, 1956650, 1956672, 1956695, 1956696, 1956697, 1956698, 1956699, 1956708, 1956709, 1956711, 1956758, 1956830, 1956831, 1956861, 1956947, 1956948, 19561014, 19561055, 19561056, 19561091, 19561101, 19561105, 19561107, 19561108, 19561112, 19561113, 19561115, 19561121, 19561127, 19561149, 19561150, 19561200, 19561201, 19561234, 19561235, 19561236, 19561251, 19561252, 196056, 196057, 196058, 196076, 1960208, 1960303, 1960355, 1960356, 1960405, 1960410, 1960411, 1960412, 1960413, 1960456, 1960461, 1960468, 1960488, 1960532, 1960569, 1960604, 1960629, 1960640, 1960641, 1960642, 1960651, 1960685, 1960727, 1960764, 1960787, 1960788, 1960789, 1960790, 1960791, 1960797, 1960798, 1960802, 1960851, 1960852, 1960853, 1960924, 1960961, 19601055, 19601104, 19601121, 19601172, 19601173, 19601174, 19601214, 19601224, 19601230, 19601234, 19601235, 19601240, 19601247, 19601253, 19601257, 19601272, 19601273, 19601287, 19601340, 19601380, 19601381, 19601382, 19601396, 196157, 196163, 196173, 1961296, 1961352, 1961354, 1961401, 1961404, 1961405, 1961406, 1961451, 1961457, 1961463, 1961486, 1961527, 1961558, 1961596, 1961622, 1961632, 1961633, 1961634, 1961647, 1961721, 1961757, 1961780, 1961781, 1961782, 1961783, 1961792, 1961793, 1961798, 1961840, 1961841, 1961881, 1961908, 1961909, 1961948, 19611040, 19611087, 19611105, 19611106, 19611148, 19611149, 19611190, 19611200, 19611206, 19611210, 19611211, 19611216, 19611220, 19611225, 19611229, 19611241, 19611255, 19611302, 19611303, 19611345, 19611346, 19611360, 19611361, 19611367, 196417, 196468, 196476, 196483, 1964275, 1964333, 1964382, 1964385, 1964386, 1964432, 1964439, 1964447, 1964467, 1964518, 1964558, 1964595, 1964624, 1964631, 1964632, 1964633, 1964647, 1964728, 1964765, 1964769, 1964795, 1964796, 1964797, 1964798, 1964810, 1964811, 1964816, 1964866, 1964867, 1964922, 1964954, 19641098, 19641183, 19641229, 19641230, 19641274, 19641282, 19641286, 19641288, 19641291, 19641292, 19641297, 19641303, 19641308, 19641329, 19641330, 19641345, 19641390, 19641433, 19641434, 19641451, 19641452, 196716, 196765, 196775, 1967264, 1967313, 1967369, 1967372, 1967373, 1967412, 1967416, 1967422, 1967439, 1967562, 1967585, 1967592, 1967593, 1967683, 1967718, 1967742, 1967743, 1967744, 1967755, 1967756, 1967762, 1967810, 1967811, 1967812, 1967862, 1967884, 19671023, 19671101, 19671141, 19671142, 19671179, 19671191, 19671194, 19671196, 19671200, 19671201, 19671208, 19671209, 19671216, 19671221, 19671243, 19671311, 19671353, 19671368, 197158, 197166, 197167, 1971231, 1971277, 1971278, 1971328, 1971331, 1971332, 1971373, 1971385, 1971406, 1971531, 1971550, 1971554, 1971555, 1971639, 1971670, 1971687, 1971688, 1971689, 1971703, 1971704, 1971709, 1971756, 1971829, 1971968, 19711042, 19711074, 19711116, 19711122, 19711124, 19711125, 19711136, 19711146, 19711166, 19711226, 19711272, 197624, 197655, 197656, 197695, 1976107, 1976117, 1976202, 1976324, 1976370, 1976390, 1976432, 1976465, 1976466, 1976480, 1976481, 1976482, 1976488, 1976526, 1976528, 1976552, 1976565, 1976688, 1976703, 1976739, 1976770, 1976783, 1976784, 1976796, 1976829, 1976831, 1976893, 1976938, 1976962, 1976986, 1976994, 19761020, 19761069, 19761070, 19761137, 19761170, 19761344, 19761345, 19761387, 19761447, 19761507, 19761568, 19761569, 19761570, 19761571, 19761572, 19761583, 19761584, 19761594, 19761595, 19761596, 19761610, 19761611, 19761621, 19761628, 19761656, 19761715, 19761736, 19761763, 19761764, 198022, 198055, 198056, 198088, 1980103, 1980112, 1980190, 1980304, 1980348, 1980412, 1980437, 1980438, 1980452, 1980453, 1980454, 1980460, 1980487, 1980493, 1980494, 1980512, 1980526, 1980662, 1980702, 1980733, 1980746, 1980747, 1980760, 1980795, 1980864, 1980906, 1980925, 1980946, 1980954, 1980978, 19801021, 19801022, 19801085, 19801086, 19801117, 19801281, 19801282, 19801313, 19801376, 19801434, 19801495, 19801496, 19801498, 19801500, 19801511, 19801513, 19801514, 19801522, 19801524, 19801525, 19801537, 19801538, 19801548, 19801553, 19801579, 19801667, 19801692, 19801693, 198225, 198257, 198258, 198297, 1982112, 1982124, 1982218, 1982351, 1982398, 1982465, 1982501, 1982502, 1982519, 1982520, 1982527, 1982528, 1982560, 1982567, 1982568, 1982589, 1982605, 1982752, 1982794, 1982824, 1982837, 1982838, 1982852, 1982890, 1982968, 19821011, 19821040, 19821062, 19821070, 19821096, 19821097, 19821142, 19821143, 19821215, 19821216, 19821250, 19821421, 19821422, 19821461, 19821595, 19821662, 19821663, 19821667, 19821680, 19821681, 19821691, 19821693, 19821694, 19821708, 19821709, 19821721, 19821727, 19821755, 19821850, 19821874, 19821875, 198427, 198461, 198493, 198494, 1984106, 1984338, 1984382, 1984483, 1984500, 1984501, 1984508, 1984547, 1984548, 1984568, 1984583, 1984763, 1984793, 1984803, 1984804, 1984817, 1984853, 1984934, 1984975, 19841010, 19841035, 19841044, 19841068, 19841110, 19841111, 19841191, 19841192, 19841193, 19841223, 19841423, 19841424, 19841529, 19841596, 19841665, 19841667, 19841670, 19841683, 19841685, 19841686, 19841696, 19841698, 19841712, 19841713, 19841725, 19841732, 19841761, 19841762, 19841878, 19841879, 19892, 198925, 198957, 198958, 1989119, 1989158, 1989159, 1989192, 1989209, 1989284, 1989391, 1989465, 1989496, 1989531, 1989552, 1989568, 1989660, 1989682, 1989683, 1989691, 1989693, 1989696, 1989723, 1989748, 1989758, 1989759, 1989786, 1989805, 1989839, 1989860, 1989921, 19891015, 19891068, 19891123, 19891124, 19891139, 19891140, 19891141, 19891163, 19891211, 19891307, 19891308, 19891321, 19891370, 19891375, 19891390, 19891409, 19891446, 19891449, 19891462, 19891495, 19891496, 19891556, 19891557, 19891661, 19891662, 19891700, 19891758, 19891759, 19891793, 19891849, 19891972, 19891973, 19892020, 19892026, 19892027, 19892037, 19892055, 19892131, 19892208, 19892209, 19892210, 19892320, 19892322, 19892325, 19892343, 19892345, 19892346, 19892356, 19892358, 19892359, 19892376, 19892377, 19892396, 19892402, 19892433, 19892461, 19892573, 19892598, 19892607, 19892609, 19892664]

In [21]:
Kreuzberg_lines_list = list()
Kreuzberg_lines_set = set()
for i, stop_id in enumerate(line_stops_df["stop_id"]):
    print(stop_id)
    if stop_id in list(Kreuzberg_stations_df["stop_id"]):
        Kreuzberg_lines_list.append(str(line_stops_df["line_id"][i]))
        Kreuzberg_lines_set.add(str(line_stops_df["line_id"][i]))

1946151
1946158
1946212
1946325
1946257
1946138
1946596
1946476
19462
19466
1946240
1946472
194613
1946172
1946301
1946153
1946157
1946156
19468
1946206
1946459
1946457
1946252
1946531
1946125
1946170
1946589
1946426
1946136
1946232
1946414
194618
1946628
1946412
194676
194683
1946539
1946600
1946556
1946436
194611
1946345
1946309
1946346
1946173
1946291
1946232
1946414
194619
1946456
1946437
194689
1946189
1946395
1946620
1946621
1946427
1946400
1946360
1946448
1946588
1946149
1946583
1946586
194632
1946142
1946143
1946133
194653
1946536
1946527
1946477
1946571
194647
1946628
1946482
1946355
194680
1946465
194678
1946553
1946134
1946135
1946178
1946187
1946336
1946337
1946279
194675
194638
1946145
1946601
1946559
1946501
1946500
1946499
1946386
1946385
194695
194657
194696
1946613
1946614
1946202
194641
194640
1946593
1946315
1946350
1946205
19462
1946476
1946573
194698
1946120
1946118
1946565
1946297
1946284
1946188
1946555
1946267
194649
1946605
1946610
1946611
194699
1946147
194645
194635
1946199
1946186
1946612
1946390
1946391
1946185
1946624
1946625
1946183
1946175
1946567
1946562
1946582
194687
1946274
1946570
1946332
19461
1946130
1946568
19468
19467
194610
194666
1946181
1946331
194627
1946248
1946247
1946106
1946402
194677
1946394
1946100
1946622
1946621
1946428
194623
1946104
1946432
1946545
194650
1946445
1946468
1946356
1946357
1946558
1946351
1946352
1946294
1946107
1946110
1946124
1946122
1946227
194664
1946228
1946366
1946550
1946126
1946548
1946127
1946546
194650
1946445
1946468
1946356
1946357
1946253
1946146
194625
194624
1946104
1946103
1946432
1946221
1946275
1946548
1946115
1946546
194650
1946445
1946468
1946356
1946357
1946253
1946146
194625
194624
1946104
1946103
1946432
1946545
194650
1946445
1946447
1946244
1946245
1946446
1946216
1946340
1946384
1946448
1946450
1946146
194625
194624
1946104
1946432
1946604
1946282
1946444
1946452
1946341
1946384
1946448
1946450
1946146
194625
194624
1946104
1946432
1946373
1946369
194690
194689
1946189
1946392
1946100
194648
1946488
1946490
1946489
1946566
1946102
1946112
1946108
1946460
1946579
1946484
1946106
1946402
1946394
1946100
194648
1946488
1946491
1946490
1946489
1946566
1946514
1946495
1946496
1946207
1946114
1946512
1946193
1946200
1946462
1946121
1946517
1946516
1946518
1946453
1946513
1946214
1946403
1946372
1946505
194665
1946549
1946387
1946268
1946188
1946592
194641
1946191
194685
1946192
1946363
1946261
1946424
19464
1946344
1946434
1946119
1946519
1946541
1946540
1946269
194658
1946537
1946608
1946611
194699
1946147
1946238
1946607
1946234
1946593
1946235
1946304
194669
1946303
19464
1946344
1946434
1946316
1946144
1946152
194632
1946405
19464
1946344
1946434
1946616
1946380
1946443
194644
194646
1946356
1946357
1946558
1946303
194668
1946304
1946315
1946230
1946503
194670
19469
1946270
1946563
1946271
1946375
1946592
194641
1946305
1946203
1946420
194679
1946421
1946424
19464
1946344
1946434
1946222
1946422
1946423
1946420
194679
1946421
1946424
19464
1946344
1946434
1946322
1946231
1946528
1946165
1946250
1946215
1946410
1946418
1946417
1946414
1946312
1946139
1946521
1946209
1946368
1946535
1946364
1946207
1946381
1946515
1946114
1946278
1946408
194612
1946162
194663
1946438
1946265
1946342
1946269
194658
1946609
1946611
1946211
1946198
1946258
1946287
1946288
194662
1946241
1946208
1946455
1946323
1946454
1946324
1946246
1946231
1946528
1946165
1946164
1946263
1946264
1946259
1946269
1946344
1946469
1946255
194614
1946354
1946533
1946339
194661
1946523
1946575
1946479
1946139
1946521
1946348
1946359
1946300
1946474
1946559
194615
1946298
194656
1946376
1946602
1946388
1946594
194616
1946326
1946293
1946353
194659
1946174
1946431
1946560
1946111
1946299
194628
1946529
1946260
1946224
1946507
1946508
1946509
194633
194656
1946298
194681
1946376
1946602
1946388
1946594
194616
1946326
1946131
1946595
1946295
1946328
1946525
1946416
1946551
1946497
1946285
1946307
194621
194674
194620
194626
1946160
194682
194643
1946166
194620
1946335
1946123
1946318
194629
194672
1946373
194689
1946189
1946397
1946621
194623
1946104
1946432
1946179
1946487
1946419
1946190
1946154
1946389
1946561
1946506
1946365
1946226
1946552
1946401
1946483
1946249
1946606
1946478
1946237
1946210
1946599
1946618
1946598
1946262
194655
1946430
1946587
1946179
1946226
1946365
1946290
194634
1946485
194654
19460
1946201
1946262
1946597
1946504
1946177
1946511
1946406
1946441
1946217
1946141
1946599
1946117
1946467
1946631
1946557
194637
1946310
1946169
1946113
19463
1946254
1946473
1946585
1946389
1946561
194634
1946485
194654
19460
1946201
1946485
1946377
1946520
194651
1946629
1946463
1946105
1946272
194691
1946398
1946399
194694
1946179
1946243
1946530
1946413
194617
1946623
1946401
1946425
1946543
1946306
1946319
1946320
1946379
1946308
194693
194688
1946233
1946171
1946229
1946578
1946615
1946603
1946493
1946619
194694
1946179
1946243
1946530
1946169
1946572
1946413
194617
1946196
1946483
1946163
1946150
1946526
194697
1946321
1946542
1946626
1946627
1946471
1946370
1946581
1946137
1946574
1946236
1946223
1946220
1946480
1946544
1946140
1946615
1946442
1946493
1946619
194694
1946179
1946243
1946530
1946413
194617
1946623
1946401
1946425
1946334
1946338
1946109
1946317
1946330
1946129
1946433
1946411
194622
1946195
1946581
1946370
1946197
1946599
1946117
1946467
1946631
1946557
194637
1946310
1946169
1946113
19463
1946254
1946473
1946585
1946389
1946361
1946314
1946168
194686
1946273
1946396
1946486
1946132
1946502
1946492
19465
1946277
1946349
1946522
1946524
1946415
1946182
1946289
1946371
1946617
1946617
1946630
1946280
1946538
1946510
1946266
1946439
1946362
1946440
1946461
1946617
1946374
1946239
1946148
1946219
1946464
1946101
1946409
1946128
1946554
1946383
1946378
1946286
1946213
1946429
1946283
1946204
1946475
1946584
1946251
194636
1946576
1946371
1946617
1946569
1946498
1946313
194684
1946449
1946481
1946532
1946382
194660
1946161
1946524
1946281
1946213
1946159
1946184
1946176
1946225
1946435
194639
1946367
1946194
1946180
1946577
194652
1946458
1946590
19465
1946256
1946358
1946347
1946283
1946494
1946225
194692
1946311
19465
1946470
1946534
1946343
1946404
1946466
1946155
1946329
194671
1946167
1946407
1946276
1946580
1951328
1951626
1951837
1951167
1951702
195129
19516
1951666
1951386
1951565
1951206
1951182
1951896
1951645
1951792
1951868
1951424
1951135
1951856
1951841
1951611
1951502
1951571
1951624
1951570
1951532
1951737
1951820
1951573
1951709
195164
1951405
1951240
1951159
1951174
195148
1951513
1951612
1951521
1951938
1951797
1951353
1951571
1951727
1951616
195152
1951367
1951457
1951662
1951777
1951156
1951877
1951707
1951816
1951790
1951213
1951621
1951298
1951467
1951886
1951157
1951427
1951877
1951785
1951707
1951436
1951135
1951856
1951311
1951671
1951333
19513
1951809
1951290
1951356
1951840
1951844
1951221
1951430
1951554
1951371
1951876
195172
1951886
1951468
195170
195171
1951371
1951412
1951489
1951248
1951741
1951529
1951699
1951509
1951507
1951279
1951356
1951110
1951117
1951544
1951524
1951292
1951792
1951643
1951463
1951158
1951609
195132
1951326
1951285
1951266
1951667
1951739
1951301
1951600
1951141
1951588
1951132
195141
1951535
1951884
195137
1951170
1951231
1951144
1951350
1951113
1951586
1951588
1951131
1951628
195186
1951801
195168
1951768
195161
1951486
1951735
1951531
1951884
1951792
1951869
1951424
1951135
1951856
1951311
1951671
1951333
1951394
1951721
1951319
1951353
1951227
1951840
195187
1951177
1951185
1951908
1951543
1951822
1951100
195193
1951295
1951171
1951802
1951236
1951269
195121
195168
1951768
195161
1951486
1951735
1951531
1951593
195186
1951679
1951346
1951352
1951269
195121
195168
1951768
195161
1951486
1951735
1951531
1951593
195186
1951679
1951743
195196
1951293
1951792
1951643
1951884
1951535
1951591
1951656
1951913
1951913
1951332
1951592
195141
195186
1951678
1951190
1951581
1951825
1951602
1951780
1951781
1951801
195168
1951768
1951698
1951803
1951337
1951591
1951572
1951593
1951831
1951678
1951694
1951644
1951791
1951291
1951827
1951916
1951407
1951440
1951240
195156
1951360
1951176
1951258
1951815
1951123
1951710
1951137
1951552
1951575
1951141
1951588
1951586
1951419
1951127
1951153
1951116
195181
1951934
1951550
1951565
1951207
1951249
1951210
1951353
1951228
1951408
1951840
1951832
1951177
1951596
1951431
1951390
1951873
1951672
1951673
1951170
1951230
1951270
1951686
1951586
1951685
1951855
1951687
1951212
1951935
1951668
1951322
1951306
1951664
1951114
195163
1951439
1951135
1951757
1951754
1951323
1951752
1951119
1951320
1951847
1951763
1951418
1951447
1951846
1951760
1951120
1951759
1951381
1951597
1951860
1951898
195196
1951799
195164
1951424
1951135
1951441
1951225
1951240
195194
1951224
1951664
1951446
1951764
1951748
195128
1951793
1951440
1951240
1951174
195148
1951670
1951333
1951691
1951483
1951366
1951568
1951892
1951784
1951683
1951468
1951471
1951422
19519
195195
1951838
1951766
1951211
1951322
1951888
1951622
195110
1951469
1951200
1951886
1951220
1951485
1951720
1951834
1951722
1951921
1951920
195161
1951486
1951532
1951716
1951535
1951322
195110
1951470
1951203
1951661
1951740
1951517
1951819
1951909
1951889
195133
1951618
1951826
1951934
1951166
1951386
1951565
1951435
1951348
1951619
1951196
1951620
19518
1951392
1951891
195133
1951316
1951202
1951690
19518
1951525
1951766
1951181
1951104
1951905
1951379
1951639
1951398
1951834
1951205
1951219
1951582
1951493
1951608
1951210
1951766
1951525
19518
1951451
1951197
195133
1951655
1951473
1951904
1951379
1951639
1951398
1951834
1951205
1951219
1951582
1951443
1951493
1951607
1951210
1951766
19518
1951451
1951197
195133
1951655
1951751
1951323
1951752
1951753
1951787
1951342
1951714
195192
1951647
195138
195127
1951696
1951135
1951377
195191
1951917
1951854
1951135
1951922
1951492
1951490
195132
1951378
1951324
1951375
1951440
1951439
1951437
1951135
1951922
1951547
1951135
1951922
1951437
1951173
1951176
1951258
1951712
1951639
1951362
1951379
195180
1951106
195144
1951659
1951287
1951480
1951482
1951289
1951659
1951208
1951379
1951780
1951176
195157
1951633
1951135
1951164
1951525
195195
1951705
1951785
1951577
1951512
195120
1951894
1951786
1951484
1951682
1951501
1951864
1951500
1951684
195183
1951364
1951454
1951445
195177
19512
195113
1951501
195199
1951484
1951445
1951862
1951150
1951415
1951715
195189
1951646
1951252
1951658
1951413
195119
1951211
1951851
1951838
1951849
1951222
195146
1951533
1951449
1951484
1951733
1951364
1951769
195183
1951253
1951631
1951782
1951399
1951384
1951205
1951218
1951582
1951836
1951614
195131
1951389
1951837
1951833
1951902
1951817
195145
1951314
1951264
1951211
1951851
1951838
1951849
1951222
195146
1951115
1951112
195135
195122
1951245
1951518
1951520
1951353
1951747
1951456
1951909
1951484
1951558
1951895
1951453
1951494
1951336
1951613
195165
1951914
1951395
195135
1951256
195123
1951807
1951126
1951852
195123
1951401
1951402
1951507
1951304
1951195
1951522
1951928
1951209
1951126
195123
1951401
1951403
195117
1951654
1951511
1951303
1951102
1951377
195191
1951917
1951854
1951135
1951922
1951547
1951583
1951726
1951199
1951738
1951487
19517
1951423
1951527
1951767
1951339
1951774
1951812
1951606
1951283
1951178
1951548
1951923
1951937
1951229
1951198
1951749
1951396
1951648
1951537
1951560
1951674
1951923
1951555
1951370
1951241
1951344
1951677
1951161
1951601
1951192
1951811
1951569
1951561
1951434
1951198
1951657
1951523
1951347
195158
1951406
1951438
1951828
1951359
1951823
1951580
1951843
195159
1951133
1951805
1951288
1951900
1951839
1951845
195190
1951223
1951907
1951191
1951853
1951810
195162
1951133
1951495
1951824
1951853
1951321
1951105
1951903
1951103
1951461
1951268
195185
195125
1951693
1951358
1951866
1951567
1951338
1951701
1951734
1951762
1951343
19510
1951637
1951758
1951273
1951274
1951272
1951885
1951882
1951432
195155
1951125
1951125
1951867
1951335
1951331
1951567
1951652
1951426
1951651
1951130
1951372
1951162
1951154
195169
195154
1951125
1951850
195136
1951242
1951433
1951640
1951330
1951307
1951491
1951546
1951310
1951636
1951382
1951175
1951823
1951663
1951848
1951257
1951397
1951814
1951638
1951745
1951103
1951556
1951689
195134
1951450
195179
195184
1951184
1951697
1951642
195162
1951321
1951361
1951244
1951775
1951744
1951460
1951461
1951530
1951625
1951183
1951455
195143
195198
1951374
1951187
1951186
195197
1951642
1951843
1951842
1951835
1951134
1951604
1951111
1951129
1951641
1951794
1951772
1951121
1951497
1951761
1951118
1951160
1951638
1951775
1951744
1951460
1951503
1951510
1951109
1951122
1951775
1951124
1951108
1951404
1951506
1951756
1951637
1951341
1951939
1951276
195140
1951275
1951540
195115
1951688
1951254
1951128
195126
1951488
1951681
1951148
1951234
1951872
1951723
1951101
1951261
1951680
1951189
1951277
195118
195188
1951149
1951718
1951871
1951881
1951232
195178
1951139
1951880
1951843
1951188
195162
1951193
1951481
1951636
1951514
1951393
1951829
1951821
1951634
1951706
1951247
1951450
1951728
1951665
1951564
1951660
1951201
1951559
1951893
1951278
1951204
1951516
1951579
1951329
1951317
1951349
195111
195114
195112
1951169
1951830
1951711
195182
1951770
1951598
1951107
1951299
1951380
1951912
1951334
1951214
1951142
1951294
1951165
1951163
195160
1951617
1951458
1951315
195153
1951890
1951238
1951239
1951235
1951233
1951731
1951761
1951421
195116
1951732
1951305
1951584
1951585
1951587
1951140
1951574
1951553
1951146
1951700
1951830
1951296
1951284
1951179
1951417
1951610
1951400
1951410
1951539
1951783
1951385
195149
1951861
1951548
1951442
1951283
1951528
1951327
1951627
1951428
1951878
1951708
1951318
1951428
1951627
1951327
1951528
1951283
1951442
1951548
1951923
1951857
1951736
1951472
195142
1951653
1951870
1951551
1951566
1951265
1951250
1951773
1951425
1951327
1951519
1951286
1951798
1951354
1951635
1951409
1951542
1951300
1951519
1951246
1951595
1951808
1951281
1951863
195167
1951669
1951887
19517
1951388
1951534
1951526
1951428
1951730
1951354
1951147
1951465
1951259
1951475
1951496
1951778
1951692
195173
1951504
1951789
1951703
19517
1951280
1951725
1951615
1951297
1951466
1951931
1951776
1951578
1951818
1951746
1951541
1951355
1951806
1951594
1951719
1951383
1951915
1951713
1951369
1951325
1951901
1951924
1951899
1951391
195176
1951629
1951883
1951280
1951915
1951383
1951719
1951594
1951806
1951355
1951541
1951444
195147
1951724
195175
19511
1951313
1951391
1951897
1951742
1951271
1951724
1951557
1951765
1951771
1951755
1951750
1951599
1951649
1951340
1951216
1951901
1951180
1951695
1951936
1951813
195150
1951464
1951263
1951515
19515
1951387
1951576
1951879
1951578
1951536
1951474
1951260
1951136
1951416
1951499
1951373
1951538
1951251
1951282
1951788
1951603
195139
1951302
1951875
1951545
1951309
1951901
1951180
1951695
1951936
1951813
195150
1951464
1951263
1951515
19515
1951387
1951576
1951879
1951578
1951675
195174
1951411
1951926
1951452
1951363
1951262
1951630
1951910
1951226
1951237
19514
1951755
1951750
1951599
1951649
1951340
1951216
1951901
1951180
1951695
1951936
1951813
195150
1951464
1951263
1951515
19515
1951387
1951576
1951879
1951578
1951818
195147
1951724
195175
19511
1951313
1951217
1951933
1951906
1951448
1951562
1951462
1951151
1951138
1951365
1951267
1951357
1951865
1951919
1951911
1951729
1951925
1951152
1951280
1951376
1951549
1951563
1951263
1951858
1951605
195130
1951308
1951719
1951255
1951243
1951779
1951155
1951479
1951795
1951929
1951930
1951704
1951545
1951875
1951929
1951368
1951351
1951345
1951717
1951800
1951215
1951918
1951650
1951729
1951925
1951152
1951280
1951376
1951549
1951563
1951263
1951858
1951605
195130
1951549
1951563
1951263
1951858
1951605
195130
1951927
1951594
1951623
1951505
1951508
1951172
1951476
1951498
1951145
1951194
1951632
195166
1951932
1951676
1951168
1951414
1951143
1951589
1951590
1951152
1951280
1951376
1951549
1951563
1951263
1951858
1951605
195130
1951927
1951594
1951623
1951796
1951459
1951477
1951478
1951804
1951420
1951874
1956944
19561026
1956628
1956625
195611
1956359
1956891
1956204
1956497
1956754
19561179
195635
19561201
1956446
19561055
1956695
1956369
1956732
19561227
1956166
195634
1956378
19561088
1956311
19561175
19561151
1956100
1956713
1956156
1956192
1956148
1956842
1956883
1956607
1956471
1956547
195647
1956822
1956973
1956178
1956725
19561055
19561251
1956695
1956813
1956688
1956220
1956308
1956572
1956523
19561220
1956656
1956767
1956378
1956804
19561129
1956761
1956829
1956404
1956713
1956156
1956401
1956321
1956101
1956621
1956798
195649
1956387
1956821
19561097
1956746
1956166
19561227
1956397
1956847
1956423
19565
19561071
1956741
1956374
1956200
1956225
19561106
19561117
19561122
1956290
1956604
19561116
1956122
195612
19561135
1956891
1956204
1956497
1956754
1956420
1956548
1956564
1956938
1956549
1956477
1956192
1956321
1956101
1956621
1956798
195649
1956387
1956821
19561097
1956746
1956250
1956136
1956678
1956487
1956679
1956489
1956354
1956323
1956449
19561117
1956875
1956144
1956252
1956960
1956140
1956889
1956739
1956580
1956194
1956781
1956923
19561134
1956929
1956275
19561248
1956891
1956700
19569
1956288
1956161
1956762
195663
1956717
19561175
1956311
195655
1956170
19561040
19561086
1956706
1956161
1956764
1956828
1956112
1956905
1956205
1956100
19561059
195699
1956278
1956581
1956653
1956981
19561175
1956569
19561043
19561086
19561099
1956166
19561227
1956397
195661
1956849
1956266
1956513
1956968
19561014
1956861
1956366
1956990
1956446
19561178
1956844
1956527
19561117
1956449
1956354
19561070
1956725
19561094
1956118
1956380
1956677
1956212
19561060
1956305
1956342
1956900
195624
195699
1956281
1956583
1956654
1956981
1956714
1956869
19561138
1956791
1956112
1956906
1956435
1956444
1956342
1956901
195624
195699
1956279
1956583
1956654
1956981
1956714
1956869
19561139
1956791
1956112
1956905
1956987
19561193
1956124
19561057
19561199
1956379
19561090
1956858
19561176
1956717
1956962
1956761
1956789
1956872
1956382
1956867
1956157
1956872
1956785
1956786
1956784
1956763
1956966
1956790
1956112
1956905
1956247
1956775
19561096
1956806
1956853
1956150
1956550
19561029
19561059
195699
1956278
1956581
1956383
195650
1956872
1956787
1956766
19561137
1956791
19561104
19561151
1956205
1956100
1956940
1956857
19561041
1956376
19561099
19561217
1956524
1956576
1956308
195689
1956458
1956223
1956331
19561079
1956150
1956953
1956169
1956728
1956737
1956769
1956580
1956198
1956781
1956923
19561134
1956929
1956275
19561248
19561155
1956497
1956754
19561179
195635
1956446
1956298
1956526
19561117
19561106
1956225
1956795
1956566
1956506
19561209
1956895
1956211
1956300
1956343
1956924
1956781
1956923
19561134
1956929
1956275
19561248
1956891
1956410
1956392
1956887
19561109
195694
19561110
19561132
1956166
1956999
19561003
1956310
1956413
19561001
1956146
19561066
19561125
1956952
1956588
1956957
1956656
19561221
19561123
1956616
19561099
1956522
1956166
19561002
19561001
1956983
1956347
19561154
1956124
1956656
19561123
1956553
1956166
1956587
19561007
1956543
1956951
1956511
19561045
1956576
1956558
19561195
1956308
1956183
19561141
195659
1956220
1956689
1956424
1956138
1956937
1956645
1956470
1956303
1956326
19561188
19561032
1956919
1956624
1956628
1956544
195612
19561135
1956411
1956392
1956469
1956759
19561188
19561032
1956919
1956623
1956628
1956544
195610
1956122
19561116
19561011
1956273
195684
1956425
1956493
19561080
1956233
195680
1956232
19561075
1956159
195629
1956433
1956581
1956654
1956981
1956961
1956717
1956504
1956596
1956143
1956742
1956431
1956915
19561078
1956950
1956127
195656
1956883
19561032
1956623
1956628
195612
1956410
1956754
19561163
1956469
19561049
19561016
1956224
195647
1956822
19561198
1956973
19561248
1956495
1956497
1956754
19561179
1956241
1956441
1956440
195637
1956824
1956925
1956261
1956932
19569
1956509
19561185
1956545
195647
1956405
1956925
1956261
1956933
19569
1956707
1956893
1956236
1956130
19561206
1956460
1956853
1956956
1956516
1956613
1956492
1956266
1956285
1956777
19561095
1956661
1956812
1956631
19561205
1956460
1956853
1956218
1956492
1956264
1956776
1956227
1956812
19561207

In [ ]:
Kreuzberg_line_ids = list()
Kreuzberg_jahrs = list()
Kreuzberg_linien_names = list()
Kreuzberg_typs = list()
Kreuzberg_dauers = list()
Kreuzberg_ost_wests = list()
Kreuzberg_frequenzs = list()
Kreuzberg_länges = list()
Kreuzberg_starts = list()
Kreuzberg_ziels = list()
for i, line_id in enumerate(lines_df["line_id"]):
    if str(line_id) in Kreuzberg_lines_set:
        Kreuzberg_line_ids.append(lines_df["line_id"][i])
        Kreuzberg_jahrs.append(lines_df["jahr"][i])
        Kreuzberg_linien_names.append(lines_df["linien_name"][i])
        Kreuzberg_typs.append(lines_df["typ"][i])
        Kreuzberg_dauers.append(lines_df["dauer (min)"][i])
        Kreuzberg_ost_wests.append(lines_df["ost_west"][i])
        Kreuzberg_frequenzs.append(lines_df["frequenz"][i])
        Kreuzberg_länges.append(lines_df["länge (km)"][i])
        Kreuzberg_starts.append(lines_df["start"][i])
        Kreuzberg_ziels.append(lines_df["ziel"][i])

19461
19462
19464
194612
194644
194648
194656
194658
194660
194662
194665
194668
194669
19511
19513
19514
19515
195110
195114
195142
195150
195151
195153
195154
195157
195159
195185
195197
195198
195199
1951100
1951101
1951110
1951112
1951113
1951114
19562
19564
195614
195648
195649
195652
195653
195657
195658
195659
195660
195673
195679
195682
195683
195695
1956118
1956120
1956121
1956122
1956134
1956137
1956138
19605
19608
196011
196044
196045
196047
196051
196052
196064
196070
196073
196074
196083
1960107
1960109
1960132
1960133
1960135
1960136
1960138
1960139
1960140
1960153
1960156
1960157
19613
196110
196111
196138
196139
196142
196143
196156
196161
196165
196166
196170
196174
1961100
1961109
1961110
1961111
1961119
1961123
1961124
1961126
1961127
1961129
1961130
1961131
1961148
1961151
1961153
196431
196433
196434
196435
196449
196454
196458
196459
196468
196498
1964108
1964109
1964110
1964111
1964123
1964138
1964139
1964143
1964144
1964145
1964149
1964151
1964152
196721
196723
196739
196745
196749
196750
196761
196797
1967107
1967123
1967129
1967130
1967138
1967139
1967143
1967144
1967145
1967150
1967151
1967152
197140
197146
197148
197149
197156
197175
197183
1971103
1971104
1971135
1971136
1971137
1971165
1971166
1971170
1971171
1971174
1971175
1971176
197615
197625
197630
197631
197654
197656
197690
1976112
1976144
1976145
1976159
1976163
1976164
1976165
1976167
1976168
1976171
198019
198031
198037
198039
198061
198065
1980114
1980115
1980143
1980145
1980162
1980166
1980167
1980168
1980170
1980171
198218
198229
198235
198236
198257
198261
1982150
1982152
1982158
1982162
1982163
1982164
1982166
1982167
198421
198433
198439
198462
198466
1984123
1984162
1984163
1984173
1984177
1984178
1984179
1984181
198921
198932
198939
198941
198953
198955
1989105
1989122
1989123
1989129
1989133
1989134
1989135
1989137
1989138

In [44]:
Kreuzberg_lines_df = pd.DataFrame({'line_id':Kreuzberg_line_ids, 'jahr':Kreuzberg_jahrs, 'linien_name':Kreuzberg_linien_names, 'typ':Kreuzberg_typs, 'dauer (min)':Kreuzberg_dauers, "ost_west":Kreuzberg_ost_wests, "frequenz":Kreuzberg_frequenzs, "länge (km)":Kreuzberg_länges, 'start':Kreuzberg_starts, 'ziel':Kreuzberg_ziels})
Kreuzberg_lines_df

,line_id,jahr,linien_name,typ,dauer (min),ost_west,frequenz,länge (km),start,ziel
0,19461,1946,1,autobus,NaN,both/unkown,25,NaN,Flughafen,Alt-Friedrichsfelde
1,19462,1946,1,straßenbahn,15.0,both/unkown,10,NaN,Hackescher Markt,Anhalter Bahnhof
2,19464,1946,21,straßenbahn,15.0,both/unkown,6,NaN,Wiebestrasse,Anhalter Bhf.
3,194612,1946,3,straßenbahn,NaN,both/unkown,10,NaN,Gotzkowskystrasse,Gardepionierplatz
4,194644,1946,87,straßenbahn,30.0,both/unkown,10,NaN,Dönhoffplatz,Rahnsdorf
...,...,...,...,...,...,...,...,...,...,...
244,1989133,1989,6,u-bahn,37.0,west,3,NaN,Tegel,Alt-Mariendorf
245,1989134,1989,7,u-bahn,56.0,west,12,NaN,Rathaus Spandau,Rudow
246,1989135,1989,8,u-bahn,27.0,west,5,NaN,Paracelsus-Bad,Leinestrasse
247,1989137,1989,1,s-bahn,30.0,west,10,NaN,Anhalter Bahnhof,Wannsee
248,1989138,1989,2,s-bahn,53.0,west,10,NaN,Frohnau,Lichtenrade

In [47]:
Kreuzberg_lines_df.to_csv("FilteredDataset/Kreuzberg_lines.csv")

In [49]:
Wilmersdorf_lines_list = list()
Wilmersdorf_lines_set = set()
for i, stop_id in enumerate(line_stops_df["stop_id"]):
    print(stop_id)
    if stop_id in list(Wilmersdorf_stations_df["stop_id"]):
        Wilmersdorf_lines_list.append(str(line_stops_df["line_id"][i]))
        Wilmersdorf_lines_set.add(str(line_stops_df["line_id"][i]))

1946151
1946158
1946212
1946325
1946257
1946138
1946596
1946476
19462
19466
1946240
1946472
194613
1946172
1946301
1946153
1946157
1946156
19468
1946206
1946459
1946457
1946252
1946531
1946125
1946170
1946589
1946426
1946136
1946232
1946414
194618
1946628
1946412
194676
194683
1946539
1946600
1946556
1946436
194611
1946345
1946309
1946346
1946173
1946291
1946232
1946414
194619
1946456
1946437
194689
1946189
1946395
1946620
1946621
1946427
1946400
1946360
1946448
1946588
1946149
1946583
1946586
194632
1946142
1946143
1946133
194653
1946536
1946527
1946477
1946571
194647
1946628
1946482
1946355
194680
1946465
194678
1946553
1946134
1946135
1946178
1946187
1946336
1946337
1946279
194675
194638
1946145
1946601
1946559
1946501
1946500
1946499
1946386
1946385
194695
194657
194696
1946613
1946614
1946202
194641
194640
1946593
1946315
1946350
1946205
19462
1946476
1946573
194698
1946120
1946118
1946565
1946297
1946284
1946188
1946555
1946267
194649
1946605
1946610
1946611
194699
1946147
194645
194635
1946199
1946186
1946612
1946390
1946391
1946185
1946624
1946625
1946183
1946175
1946567
1946562
1946582
194687
1946274
1946570
1946332
19461
1946130
1946568
19468
19467
194610
194666
1946181
1946331
194627
1946248
1946247
1946106
1946402
194677
1946394
1946100
1946622
1946621
1946428
194623
1946104
1946432
1946545
194650
1946445
1946468
1946356
1946357
1946558
1946351
1946352
1946294
1946107
1946110
1946124
1946122
1946227
194664
1946228
1946366
1946550
1946126
1946548
1946127
1946546
194650
1946445
1946468
1946356
1946357
1946253
1946146
194625
194624
1946104
1946103
1946432
1946221
1946275
1946548
1946115
1946546
194650
1946445
1946468
1946356
1946357
1946253
1946146
194625
194624
1946104
1946103
1946432
1946545
194650
1946445
1946447
1946244
1946245
1946446
1946216
1946340
1946384
1946448
1946450
1946146
194625
194624
1946104
1946432
1946604
1946282
1946444
1946452
1946341
1946384
1946448
1946450
1946146
194625
194624
1946104
1946432
1946373
1946369
194690
194689
1946189
1946392
1946100
194648
1946488
1946490
1946489
1946566
1946102
1946112
1946108
1946460
1946579
1946484
1946106
1946402
1946394
1946100
194648
1946488
1946491
1946490
1946489
1946566
1946514
1946495
1946496
1946207
1946114
1946512
1946193
1946200
1946462
1946121
1946517
1946516
1946518
1946453
1946513
1946214
1946403
1946372
1946505
194665
1946549
1946387
1946268
1946188
1946592
194641
1946191
194685
1946192
1946363
1946261
1946424
19464
1946344
1946434
1946119
1946519
1946541
1946540
1946269
194658
1946537
1946608
1946611
194699
1946147
1946238
1946607
1946234
1946593
1946235
1946304
194669
1946303
19464
1946344
1946434
1946316
1946144
1946152
194632
1946405
19464
1946344
1946434
1946616
1946380
1946443
194644
194646
1946356
1946357
1946558
1946303
194668
1946304
1946315
1946230
1946503
194670
19469
1946270
1946563
1946271
1946375
1946592
194641
1946305
1946203
1946420
194679
1946421
1946424
19464
1946344
1946434
1946222
1946422
1946423
1946420
194679
1946421
1946424
19464
1946344
1946434
1946322
1946231
1946528
1946165
1946250
1946215
1946410
1946418
1946417
1946414
1946312
1946139
1946521
1946209
1946368
1946535
1946364
1946207
1946381
1946515
1946114
1946278
1946408
194612
1946162
194663
1946438
1946265
1946342
1946269
194658
1946609
1946611
1946211
1946198
1946258
1946287
1946288
194662
1946241
1946208
1946455
1946323
1946454
1946324
1946246
1946231
1946528
1946165
1946164
1946263
1946264
1946259
1946269
1946344
1946469
1946255
194614
1946354
1946533
1946339
194661
1946523
1946575
1946479
1946139
1946521
1946348
1946359
1946300
1946474
1946559
194615
1946298
194656
1946376
1946602
1946388
1946594
194616
1946326
1946293
1946353
194659
1946174
1946431
1946560
1946111
1946299
194628
1946529
1946260
1946224
1946507
1946508
1946509
194633
194656
1946298
194681
1946376
1946602
1946388
1946594
194616
1946326
1946131
1946595
1946295
1946328
1946525
1946416
1946551
1946497
1946285
1946307
194621
194674
194620
194626
1946160
194682
194643
1946166
194620
1946335
1946123
1946318
194629
194672
1946373
194689
1946189
1946397
1946621
194623
1946104
1946432
1946179
1946487
1946419
1946190
1946154
1946389
1946561
1946506
1946365
1946226
1946552
1946401
1946483
1946249
1946606
1946478
1946237
1946210
1946599
1946618
1946598
1946262
194655
1946430
1946587
1946179
1946226
1946365
1946290
194634
1946485
194654
19460
1946201
1946262
1946597
1946504
1946177
1946511
1946406
1946441
1946217
1946141
1946599
1946117
1946467
1946631
1946557
194637
1946310
1946169
1946113
19463
1946254
1946473
1946585
1946389
1946561
194634
1946485
194654
19460
1946201
1946485
1946377
1946520
194651
1946629
1946463
1946105
1946272
194691
1946398
1946399
194694
1946179
1946243
1946530
1946413
194617
1946623
1946401
1946425
1946543
1946306
1946319
1946320
1946379
1946308
194693
194688
1946233
1946171
1946229
1946578
1946615
1946603
1946493
1946619
194694
1946179
1946243
1946530
1946169
1946572
1946413
194617
1946196
1946483
1946163
1946150
1946526
194697
1946321
1946542
1946626
1946627
1946471
1946370
1946581
1946137
1946574
1946236
1946223
1946220
1946480
1946544
1946140
1946615
1946442
1946493
1946619
194694
1946179
1946243
1946530
1946413
194617
1946623
1946401
1946425
1946334
1946338
1946109
1946317
1946330
1946129
1946433
1946411
194622
1946195
1946581
1946370
1946197
1946599
1946117
1946467
1946631
1946557
194637
1946310
1946169
1946113
19463
1946254
1946473
1946585
1946389
1946361
1946314
1946168
194686
1946273
1946396
1946486
1946132
1946502
1946492
19465
1946277
1946349
1946522
1946524
1946415
1946182
1946289
1946371
1946617
1946617
1946630
1946280
1946538
1946510
1946266
1946439
1946362
1946440
1946461
1946617
1946374
1946239
1946148
1946219
1946464
1946101
1946409
1946128
1946554
1946383
1946378
1946286
1946213
1946429
1946283
1946204
1946475
1946584
1946251
194636
1946576
1946371
1946617
1946569
1946498
1946313
194684
1946449
1946481
1946532
1946382
194660
1946161
1946524
1946281
1946213
1946159
1946184
1946176
1946225
1946435
194639
1946367
1946194
1946180
1946577
194652
1946458
1946590
19465
1946256
1946358
1946347
1946283
1946494
1946225
194692
1946311
19465
1946470
1946534
1946343
1946404
1946466
1946155
1946329
194671
1946167
1946407
1946276
1946580
1951328
1951626
1951837
1951167
1951702
195129
19516
1951666
1951386
1951565
1951206
1951182
1951896
1951645
1951792
1951868
1951424
1951135
1951856
1951841
1951611
1951502
1951571
1951624
1951570
1951532
1951737
1951820
1951573
1951709
195164
1951405
1951240
1951159
1951174
195148
1951513
1951612
1951521
1951938
1951797
1951353
1951571
1951727
1951616
195152
1951367
1951457
1951662
1951777
1951156
1951877
1951707
1951816
1951790
1951213
1951621
1951298
1951467
1951886
1951157
1951427
1951877
1951785
1951707
1951436
1951135
1951856
1951311
1951671
1951333
19513
1951809
1951290
1951356
1951840
1951844
1951221
1951430
1951554
1951371
1951876
195172
1951886
1951468
195170
195171
1951371
1951412
1951489
1951248
1951741
1951529
1951699
1951509
1951507
1951279
1951356
1951110
1951117
1951544
1951524
1951292
1951792
1951643
1951463
1951158
1951609
195132
1951326
1951285
1951266
1951667
1951739
1951301
1951600
1951141
1951588
1951132
195141
1951535
1951884
195137
1951170
1951231
1951144
1951350
1951113
1951586
1951588
1951131
1951628
195186
1951801
195168
1951768
195161
1951486
1951735
1951531
1951884
1951792
1951869
1951424
1951135
1951856
1951311
1951671
1951333
1951394
1951721
1951319
1951353
1951227
1951840
195187
1951177
1951185
1951908
1951543
1951822
1951100
195193
1951295
1951171
1951802
1951236
1951269
195121
195168
1951768
195161
1951486
1951735
1951531
1951593
195186
1951679
1951346
1951352
1951269
195121
195168
1951768
195161
1951486
1951735
1951531
1951593
195186
1951679
1951743
195196
1951293
1951792
1951643
1951884
1951535
1951591
1951656
1951913
1951913
1951332
1951592
195141
195186
1951678
1951190
1951581
1951825
1951602
1951780
1951781
1951801
195168
1951768
1951698
1951803
1951337
1951591
1951572
1951593
1951831
1951678
1951694
1951644
1951791
1951291
1951827
1951916
1951407
1951440
1951240
195156
1951360
1951176
1951258
1951815
1951123
1951710
1951137
1951552
1951575
1951141
1951588
1951586
1951419
1951127
1951153
1951116
195181
1951934
1951550
1951565
1951207
1951249
1951210
1951353
1951228
1951408
1951840
1951832
1951177
1951596
1951431
1951390
1951873
1951672
1951673
1951170
1951230
1951270
1951686
1951586
1951685
1951855
1951687
1951212
1951935
1951668
1951322
1951306
1951664
1951114
195163
1951439
1951135
1951757
1951754
1951323
1951752
1951119
1951320
1951847
1951763
1951418
1951447
1951846
1951760
1951120
1951759
1951381
1951597
1951860
1951898
195196
1951799
195164
1951424
1951135
1951441
1951225
1951240
195194
1951224
1951664
1951446
1951764
1951748
195128
1951793
1951440
1951240
1951174
195148
1951670
1951333
1951691
1951483
1951366
1951568
1951892
1951784
1951683
1951468
1951471
1951422
19519
195195
1951838
1951766
1951211
1951322
1951888
1951622
195110
1951469
1951200
1951886
1951220
1951485
1951720
1951834
1951722
1951921
1951920
195161
1951486
1951532
1951716
1951535
1951322
195110
1951470
1951203
1951661
1951740
1951517
1951819
1951909
1951889
195133
1951618
1951826
1951934
1951166
1951386
1951565
1951435
1951348
1951619
1951196
1951620
19518
1951392
1951891
195133
1951316
1951202
1951690
19518
1951525
1951766
1951181
1951104
1951905
1951379
1951639
1951398
1951834
1951205
1951219
1951582
1951493
1951608
1951210
1951766
1951525
19518
1951451
1951197
195133
1951655
1951473
1951904
1951379
1951639
1951398
1951834
1951205
1951219
1951582
1951443
1951493
1951607
1951210
1951766
19518
1951451
1951197
195133
1951655
1951751
1951323
1951752
1951753
1951787
1951342
1951714
195192
1951647
195138
195127
1951696
1951135
1951377
195191
1951917
1951854
1951135
1951922
1951492
1951490
195132
1951378
1951324
1951375
1951440
1951439
1951437
1951135
1951922
1951547
1951135
1951922
1951437
1951173
1951176
1951258
1951712
1951639
1951362
1951379
195180
1951106
195144
1951659
1951287
1951480
1951482
1951289
1951659
1951208
1951379
1951780
1951176
195157
1951633
1951135
1951164
1951525
195195
1951705
1951785
1951577
1951512
195120
1951894
1951786
1951484
1951682
1951501
1951864
1951500
1951684
195183
1951364
1951454
1951445
195177
19512
195113
1951501
195199
1951484
1951445
1951862
1951150
1951415
1951715
195189
1951646
1951252
1951658
1951413
195119
1951211
1951851
1951838
1951849
1951222
195146
1951533
1951449
1951484
1951733
1951364
1951769
195183
1951253
1951631
1951782
1951399
1951384
1951205
1951218
1951582
1951836
1951614
195131
1951389
1951837
1951833
1951902
1951817
195145
1951314
1951264
1951211
1951851
1951838
1951849
1951222
195146
1951115
1951112
195135
195122
1951245
1951518
1951520
1951353
1951747
1951456
1951909
1951484
1951558
1951895
1951453
1951494
1951336
1951613
195165
1951914
1951395
195135
1951256
195123
1951807
1951126
1951852
195123
1951401
1951402
1951507
1951304
1951195
1951522
1951928
1951209
1951126
195123
1951401
1951403
195117
1951654
1951511
1951303
1951102
1951377
195191
1951917
1951854
1951135
1951922
1951547
1951583
1951726
1951199
1951738
1951487
19517
1951423
1951527
1951767
1951339
1951774
1951812
1951606
1951283
1951178
1951548
1951923
1951937
1951229
1951198
1951749
1951396
1951648
1951537
1951560
1951674
1951923
1951555
1951370
1951241
1951344
1951677
1951161
1951601
1951192
1951811
1951569
1951561
1951434
1951198
1951657
1951523
1951347
195158
1951406
1951438
1951828
1951359
1951823
1951580
1951843
195159
1951133
1951805
1951288
1951900
1951839
1951845
195190
1951223
1951907
1951191
1951853
1951810
195162
1951133
1951495
1951824
1951853
1951321
1951105
1951903
1951103
1951461
1951268
195185
195125
1951693
1951358
1951866
1951567
1951338
1951701
1951734
1951762
1951343
19510
1951637
1951758
1951273
1951274
1951272
1951885
1951882
1951432
195155
1951125
1951125
1951867
1951335
1951331
1951567
1951652
1951426
1951651
1951130
1951372
1951162
1951154
195169
195154
1951125
1951850
195136
1951242
1951433
1951640
1951330
1951307
1951491
1951546
1951310
1951636
1951382
1951175
1951823
1951663
1951848
1951257
1951397
1951814
1951638
1951745
1951103
1951556
1951689
195134
1951450
195179
195184
1951184
1951697
1951642
195162
1951321
1951361
1951244
1951775
1951744
1951460
1951461
1951530
1951625
1951183
1951455
195143
195198
1951374
1951187
1951186
195197
1951642
1951843
1951842
1951835
1951134
1951604
1951111
1951129
1951641
1951794
1951772
1951121
1951497
1951761
1951118
1951160
1951638
1951775
1951744
1951460
1951503
1951510
1951109
1951122
1951775
1951124
1951108
1951404
1951506
1951756
1951637
1951341
1951939
1951276
195140
1951275
1951540
195115
1951688
1951254
1951128
195126
1951488
1951681
1951148
1951234
1951872
1951723
1951101
1951261
1951680
1951189
1951277
195118
195188
1951149
1951718
1951871
1951881
1951232
195178
1951139
1951880
1951843
1951188
195162
1951193
1951481
1951636
1951514
1951393
1951829
1951821
1951634
1951706
1951247
1951450
1951728
1951665
1951564
1951660
1951201
1951559
1951893
1951278
1951204
1951516
1951579
1951329
1951317
1951349
195111
195114
195112
1951169
1951830
1951711
195182
1951770
1951598
1951107
1951299
1951380
1951912
1951334
1951214
1951142
1951294
1951165
1951163
195160
1951617
1951458
1951315
195153
1951890
1951238
1951239
1951235
1951233
1951731
1951761
1951421
195116
1951732
1951305
1951584
1951585
1951587
1951140
1951574
1951553
1951146
1951700
1951830
1951296
1951284
1951179
1951417
1951610
1951400
1951410
1951539
1951783
1951385
195149
1951861
1951548
1951442
1951283
1951528
1951327
1951627
1951428
1951878
1951708
1951318
1951428
1951627
1951327
1951528
1951283
1951442
1951548
1951923
1951857
1951736
1951472
195142
1951653
1951870
1951551
1951566
1951265
1951250
1951773
1951425
1951327
1951519
1951286
1951798
1951354
1951635
1951409
1951542
1951300
1951519
1951246
1951595
1951808
1951281
1951863
195167
1951669
1951887
19517
1951388
1951534
1951526
1951428
1951730
1951354
1951147
1951465
1951259
1951475
1951496
1951778
1951692
195173
1951504
1951789
1951703
19517
1951280
1951725
1951615
1951297
1951466
1951931
1951776
1951578
1951818
1951746
1951541
1951355
1951806
1951594
1951719
1951383
1951915
1951713
1951369
1951325
1951901
1951924
1951899
1951391
195176
1951629
1951883
1951280
1951915
1951383
1951719
1951594
1951806
1951355
1951541
1951444
195147
1951724
195175
19511
1951313
1951391
1951897
1951742
1951271
1951724
1951557
1951765
1951771
1951755
1951750
1951599
1951649
1951340
1951216
1951901
1951180
1951695
1951936
1951813
195150
1951464
1951263
1951515
19515
1951387
1951576
1951879
1951578
1951536
1951474
1951260
1951136
1951416
1951499
1951373
1951538
1951251
1951282
1951788
1951603
195139
1951302
1951875
1951545
1951309
1951901
1951180
1951695
1951936
1951813
195150
1951464
1951263
1951515
19515
1951387
1951576
1951879
1951578
1951675
195174
1951411
1951926
1951452
1951363
1951262
1951630
1951910
1951226
1951237
19514
1951755
1951750
1951599
1951649
1951340
1951216
1951901
1951180
1951695
1951936
1951813
195150
1951464
1951263
1951515
19515
1951387
1951576
1951879
1951578
1951818
195147
1951724
195175
19511
1951313
1951217
1951933
1951906
1951448
1951562
1951462
1951151
1951138
1951365
1951267
1951357
1951865
1951919
1951911
1951729
1951925
1951152
1951280
1951376
1951549
1951563
1951263
1951858
1951605
195130
1951308
1951719
1951255
1951243
1951779
1951155
1951479
1951795
1951929
1951930
1951704
1951545
1951875
1951929
1951368
1951351
1951345
1951717
1951800
1951215
1951918
1951650
1951729
1951925
1951152
1951280
1951376
1951549
1951563
1951263
1951858
1951605
195130
1951549
1951563
1951263
1951858
1951605
195130
1951927
1951594
1951623
1951505
1951508
1951172
1951476
1951498
1951145
1951194
1951632
195166
1951932
1951676
1951168
1951414
1951143
1951589
1951590
1951152
1951280
1951376
1951549
1951563
1951263
1951858
1951605
195130
1951927
1951594
1951623
1951796
1951459
1951477
1951478
1951804
1951420
1951874
1956944
19561026
1956628
1956625
195611
1956359
1956891
1956204
1956497
1956754
19561179
195635
19561201
1956446
19561055
1956695
1956369
1956732
19561227
1956166
195634
1956378
19561088
1956311
19561175
19561151
1956100
1956713
1956156
1956192
1956148
1956842
1956883
1956607
1956471
1956547
195647
1956822
1956973
1956178
1956725
19561055
19561251
1956695
1956813
1956688
1956220
1956308
1956572
1956523
19561220
1956656
1956767
1956378
1956804
19561129
1956761
1956829
1956404
1956713
1956156
1956401
1956321
1956101
1956621
1956798
195649
1956387
1956821
19561097
1956746
1956166
19561227
1956397
1956847
1956423
19565
19561071
1956741
1956374
1956200
1956225
19561106
19561117
19561122
1956290
1956604
19561116
1956122
195612
19561135
1956891
1956204
1956497
1956754
1956420
1956548
1956564
1956938
1956549
1956477
1956192
1956321
1956101
1956621
1956798
195649
1956387
1956821
19561097
1956746
1956250
1956136
1956678
1956487
1956679
1956489
1956354
1956323
1956449
19561117
1956875
1956144
1956252
1956960
1956140
1956889
1956739
1956580
1956194
1956781
1956923
19561134
1956929
1956275
19561248
1956891
1956700
19569
1956288
1956161
1956762
195663
1956717
19561175
1956311
195655
1956170
19561040
19561086
1956706
1956161
1956764
1956828
1956112
1956905
1956205
1956100
19561059
195699
1956278
1956581
1956653
1956981
19561175
1956569
19561043
19561086
19561099
1956166
19561227
1956397
195661
1956849
1956266
1956513
1956968
19561014
1956861
1956366
1956990
1956446
19561178
1956844
1956527
19561117
1956449
1956354
19561070
1956725
19561094
1956118
1956380
1956677
1956212
19561060
1956305
1956342
1956900
195624
195699
1956281
1956583
1956654
1956981
1956714
1956869
19561138
1956791
1956112
1956906
1956435
1956444
1956342
1956901
195624
195699
1956279
1956583
1956654
1956981
1956714
1956869
19561139
1956791
1956112
1956905
1956987
19561193
1956124
19561057
19561199
1956379
19561090
1956858
19561176
1956717
1956962
1956761
1956789
1956872
1956382
1956867
1956157
1956872
1956785
1956786
1956784
1956763
1956966
1956790
1956112
1956905
1956247
1956775
19561096
1956806
1956853
1956150
1956550
19561029
19561059
195699
1956278
1956581
1956383
195650
1956872
1956787
1956766
19561137
1956791
19561104
19561151
1956205
1956100
1956940
1956857
19561041
1956376
19561099
19561217
1956524
1956576
1956308
195689
1956458
1956223
1956331
19561079
1956150
1956953
1956169
1956728
1956737
1956769
1956580
1956198
1956781
1956923
19561134
1956929
1956275
19561248
19561155
1956497
1956754
19561179
195635
1956446
1956298
1956526
19561117
19561106
1956225
1956795
1956566
1956506
19561209
1956895
1956211
1956300
1956343
1956924
1956781
1956923
19561134
1956929
1956275
19561248
1956891
1956410
1956392
1956887
19561109
195694
19561110
19561132
1956166
1956999
19561003
1956310
1956413
19561001
1956146
19561066
19561125
1956952
1956588
1956957
1956656
19561221
19561123
1956616
19561099
1956522
1956166
19561002
19561001
1956983
1956347
19561154
1956124
1956656
19561123
1956553
1956166
1956587
19561007
1956543
1956951
1956511
19561045
1956576
1956558
19561195
1956308
1956183
19561141
195659
1956220
1956689
1956424
1956138
1956937
1956645
1956470
1956303
1956326
19561188
19561032
1956919
1956624
1956628
1956544
195612
19561135
1956411
1956392
1956469
1956759
19561188
19561032
1956919
1956623
1956628
1956544
195610
1956122
19561116
19561011
1956273
195684
1956425
1956493
19561080
1956233
195680
1956232
19561075
1956159
195629
1956433
1956581
1956654
1956981
1956961
1956717
1956504
1956596
1956143
1956742
1956431
1956915
19561078
1956950
1956127
195656
1956883
19561032
1956623
1956628
195612
1956410
1956754
19561163
1956469
19561049
19561016
1956224
195647
1956822
19561198
1956973
19561248
1956495
1956497
1956754
19561179
1956241
1956441
1956440
195637
1956824
1956925
1956261
1956932
19569
1956509
19561185
1956545
195647
1956405
1956925
1956261
1956933
19569
1956707
1956893
1956236
1956130
19561206
1956460
1956853
1956956
1956516
1956613
1956492
1956266
1956285
1956777
19561095
1956661
1956812
1956631
19561205
1956460
1956853
1956218
1956492
1956264
1956776
1956227
1956812
19561207

In [50]:
Wilmersdorf_line_ids = list()
Wilmersdorf_jahrs = list()
Wilmersdorf_linien_names = list()
Wilmersdorf_typs = list()
Wilmersdorf_dauers = list()
Wilmersdorf_ost_wests = list()
Wilmersdorf_frequenzs = list()
Wilmersdorf_länges = list()
Wilmersdorf_starts = list()
Wilmersdorf_ziels = list()
for i, line_id in enumerate(lines_df["line_id"]):
    if str(line_id) in Wilmersdorf_lines_set:
        Wilmersdorf_line_ids.append(lines_df["line_id"][i])
        Wilmersdorf_jahrs.append(lines_df["jahr"][i])
        Wilmersdorf_linien_names.append(lines_df["linien_name"][i])
        Wilmersdorf_typs.append(lines_df["typ"][i])
        Wilmersdorf_dauers.append(lines_df["dauer (min)"][i])
        Wilmersdorf_ost_wests.append(lines_df["ost_west"][i])
        Wilmersdorf_frequenzs.append(lines_df["frequenz"][i])
        Wilmersdorf_länges.append(lines_df["länge (km)"][i])
        Wilmersdorf_starts.append(lines_df["start"][i])
        Wilmersdorf_ziels.append(lines_df["ziel"][i])

In [51]:
Wilmersdorf_lines_df = pd.DataFrame({'line_id':Wilmersdorf_line_ids, 'jahr':Wilmersdorf_jahrs, 'linien_name':Wilmersdorf_linien_names, 'typ':Wilmersdorf_typs, 'dauer (min)':Wilmersdorf_dauers, "ost_west":Wilmersdorf_ost_wests, "frequenz":Wilmersdorf_frequenzs, "länge (km)":Wilmersdorf_länges, 'start':Wilmersdorf_starts, 'ziel':Wilmersdorf_ziels})
Wilmersdorf_lines_df

,line_id,jahr,linien_name,typ,dauer (min),ost_west,frequenz,länge (km),start,ziel
0,194612,1946,3,straßenbahn,NaN,both/unkown,10,NaN,Gotzkowskystrasse,Gardepionierplatz
1,194629,1946,62,straßenbahn,20.0,both/unkown,15,NaN,"Charlottenburg, Königin-Elisabeht-Strasse","Wilmersdorf, Emser Platz"
2,194640,1946,77,straßenbahn,NaN,both/unkown,10,NaN,"Lichterfelde-Süde, Goerzallee Ecke Appenzeller...",Kantstrasse
3,194650,1946,KBS 100,s-bahn,NaN,both/unkown,10,NaN,Gesundbrunnen,Gesundbrunnen
4,194664,1946,A2,u-bahn,10.0,both/unkown,10,NaN,Wittenbergplatz,Krumme Lanke
...,...,...,...,...,...,...,...,...,...,...
195,198991,1989,74,autobus,55.0,West,20,NaN,Charlottenburg Pulsstrasse,Lindenhof
196,1989109,1989,86,autobus,55.0,West,10,NaN,S-Bhf. Grunewald,Celsiusstrasse
197,1989130,1989,2,u-bahn,20.0,west,5,NaN,Wittenbergplatz,Krumme Lanke
198,1989134,1989,7,u-bahn,56.0,west,12,NaN,Rathaus Spandau,Rudow
199,1989136,1989,9,u-bahn,22.0,west,3,NaN,Osloer Strasse,Rathaus Steglitz

In [52]:
Wilmersdorf_lines_df.to_csv("FilteredDataset/Wilmersdorf_lines.csv")